### PR TITLE
[Merged by Bors] - Bump clap to 4.0

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

Normal functionality as well as auto-completion tested successfully.

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by fhennig — CHANGES_REQUESTED** [review]
The changes that have been made look good so far. There are a lot of deprecation warnings though that I think would be good to fix already. Run

    cargo check --features clap/deprecated

To see what needs fixing. Obviously not all of these are necessary to fix now, but I think we can go for the low-haning fruit at least

Also, the changelog suggests to include unit tests using `debug_assert`:

    #[derive(clap::Parser)]
    struct Cli {
        ...
    }
    
    #[test]
    fn verify_cli() {
        use clap::CommandFactory;
        Cli::command().debug_assert()
    }

**Comment by sbernauer** [comment]
many thx, feedback adressed

**Review by fhennig — APPROVED** [review]
LGTM!

**Pull request closed without merging**
