### PR TITLE
[Merged by Bors] - Update k8s service port names accoring to arch meeting decision

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

According to arch meeting decision from 2022/09/10
```
In case a single http port call it http
If you have multiple http ports call it http-ui
```

Related to
https://github.com/stackabletech/superset-operator/issues/248
https://github.com/stackabletech/airflow-operator/issues/146

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by nightkr — APPROVED** [review]

**Comment by teozkr** [comment]
I think the port naming stuff might be better suited for somewhere in the docs repo?

I'm also not quite sure about the guidance.. on second thought it might make sense to do something like:

1. The UI should _always_ be on `http`
2. The HTTP API should be on `http-api`, unless it's just a separate endpoint on the UI port

But I could also see an argument for flipping this around (the API "owns" `http` and the UI should be on `http-ui`). I don't think this requires a full arch meeting roundtrip though, we just need to make a decision.

**Comment by sbernauer** [comment]
I'm fine with both. I only think we need to keep in mind that their can be multiple exposed apis

**Comment by sbernauer** [comment]
I removed the docs on how to name svc ports. Now this PR should be self contained and we can decide on how to call the ports independently.

**Comment by sbernauer** [comment]
Actually what do you think about using the following?
This solution should be the most flexible
```
// TODO: Consolidate web-ui port names in operators based on decision in arch meeting from 2022/08/10
// For Superset: https://github.com/stackabletech/superset-operator/issues/248
// For Airflow: https://github.com/stackabletech/airflow-operator/issues/146
// As we still support older operator versions we need to also include the "old" way of naming
let endpoint = if port_name.contains("http")
    || port_name == "ui"
    || port_name == "airflow"
    || port_name == "superset"
{
    format!("http://{node_ip}:{node_port}")
} else if port_name.contains("https") {
    format!("https://{node_ip}:{node_port}")
} else {
    format!("{node_ip}:{node_port}")
};
```

**Comment by sbernauer** [comment]
@teozkr could you please take another look?

**Comment by teozkr** [comment]
Makes sense to me. One nit is that I'd rather do `port_name == "http" || port_name.starts_with("http-")` than `port_name.contains("http")`. For example, the latter would also consider `https` to be a http port, which is clearly nonsense.

**Comment by sbernauer** [comment]
Sounds good :+1: 
Adopting PR

**Comment by sbernauer** [comment]
@teozkr please review

**Review by nightkr — APPROVED** [review]
:shipit:

**Comment by sbernauer** [comment]
Thanks a lot!

**Pull request closed without merging**
