### PR TITLE
[Merged by Bors] - Release 22.11

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

I did run all demos and they worked fine.
I personally would wait for 22.11 to be official before merging but this PR can already be tested
Did change as well:

* Update the products
* Credentials to be admin:adminadmin in most places

Use `stackablectl --additional-stacks-file stacks/stacks-v1.yaml --additional-demos-file demos/demos-v1.yaml demo install data-warehouse-iceberg-trino-spark` to run

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by adwk67 — APPROVED** [review]
LGTM % TODOs

**Comment by sbernauer** [comment]
For the record: I still need to update the credentials in the docs

**Comment by sbernauer** [comment]
@adwk67 should be ready to merge

**Review by adwk67 — APPROVED** [review]
LGTM

**Pull request closed without merging**
