### PR TITLE
[Merged by Bors] - Fix link in docs

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by fhennig — APPROVED** [review]

**Comment by teozkr** [comment]
Do we really want to version the demos independently of stackablectl itself?

**Comment by sbernauer** [comment]
@teozkr I would say so, yes. We already added 3 demos and it would be strange to always ship a >100MB binary.
Also the demo are retrieved via the Internet and the users can specify their own release/stack/demo, so stackablectl needs to access demos that are not shipped via the binary anyway

**Comment by sbernauer** [comment]
As the link is currently broken and the target is already given i would merge this now, but happy to continue the discussion :)

**Comment by teozkr** [comment]
Ok.

**Pull request closed without merging**
