### PR TITLE
chore: Remove demo and stack files

### PR DESCRIPTION
**Pull request by Techassi**
Part of https://github.com/stackabletech/issues/issues/455

### CODE REVIEW

**Comment by sbernauer** [comment]
Just for the record: We need to be aware that merging this will break "old" stackablectl versions.
IMHO we should at least keep https://github.com/stackabletech/stackablectl/blob/b71ca62337d4bef92d159ea4cf76502b51faae5e/stacks/stacks-v1.yaml and add a similar notice to stacks-v2.yaml (same demo files)

**Comment by Techassi** [comment]
Yes, this will break old stackablectl. I quite like the notice. I will add it to this PR!

**Comment by Techassi** [comment]
I updated the stack and demo definition files. Both versions now point to the documentation on how to get started with the new stackablectl version.

**Comment by sbernauer** [comment]
Thanks!

**Review by sbernauer — APPROVED** [review]
Please update https://docs.stackable.tech/management/stable/stackablectl/installation.html to install 23.11.1 before merging

**Comment by Techassi** [comment]
PR has landed: https://github.com/stackabletech/stackable-cockpit/pull/159

**Pull request merged**
