### PR TITLE
[Merged by Bors] - Add bors.toml

### PR DESCRIPTION
**Pull request by sbernauer**

### CODE REVIEW

**Review by soenkeliebau — DISMISSED** [review]

**Comment by teozkr** [comment]
Do we not want to just run templating on this repo too?

**Comment by sbernauer** [comment]
Hmm I think we have more differences than similarities. No Makefile, other releases (build binaries and attach them to the Release), in general other workflows.
But having it would be great

**Comment by sbernauer** [comment]
bors retry

**Review by soenkeliebau — APPROVED** [review]

**Comment by sbernauer** [comment]
bors retry

**Comment by sbernauer** [comment]
bors retry

**Pull request closed without merging**
