### PR TITLE
Add regorule-operator to 22.05-sbernauer

### PR DESCRIPTION
**Pull request by sbernauer**

### CODE REVIEW

**Comment by teozkr** [comment]
Wasn't this merged into the OPA operator?

**Comment by maltesander** [comment]
> Wasn't this merged into the OPA operator?

Yes but Trino 3.1 has a watch on RegoRule. Im more for releasing Trino 0.4.0 and skip the rego dependency.

**Review by maltesander — APPROVED** [review]
Ok convinced!

**Comment by soenkeliebau** [comment]
If we don't add the dependency then we should remove trino from this release though. In the current release the operator is broken and won't work.

**Comment by sbernauer** [comment]
I'm working on implementing commands to interact with stacks. In my feature-branch i upgraded Trino to `0.3.2-nightly` and everything works fine. So i suggest taking the step forward of updating Trino and putting Trino 0.4.0 in when it's available

**Pull request closed without merging**
