### PR TITLE
[Merged by Bors] - Reduce water-level request rate in NiFI workflow

### LINKED ISSUE #170: Make sure no demo misuses external APIs
We need to make sure that we are good netizens and every external API we call should be called with a really low rate limit.

### LINKED ISSUE #309: Don't use derby for metadata storage as a default
While improving demos I had a Druid instance running for 3-4 days on Ionos k8s. Suddenly everything (all datasources, ingestion tasks etc) were gone. The k8s has restarted all Pods - i assume a maintenance window. I had a look and after looking at https://druid.apache.org/docs/latest/dependencies/metadata-storage.html i think all the data is still on S3 but the metadata is lost.
I think we should prevent users from running into the same problem. I can make the demo resilient by putting a Postgres below, but i think we should address this at the druid-operator level already.
Like

- [x] All the examples (also in docs) use a postgres as metadata storage
- [ ] All the demos using Druid use a postgres as metadata storage
- [x] Make a decision if users even should have the possibility to configure a derby instance or not. Implement accordingly => They do and that's ok. Everything is fine. I'm stupid

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

* Fixes https://github.com/stackabletech/stackablectl/issues/170 by asking every 15 min for the data of the last 30 minutes
* Fixes https://github.com/stackabletech/druid-operator/issues/309 by switching to a Postgres
* Uncovered a bug https://github.com/stackabletech/druid-operator/issues/359

image

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM. Dont forget to change the urls back!

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by sbernauer** [comment]
bors cancel

**Pull request closed without merging**
