### PR TITLE
[Merged by Bors] - Print CLI tables using comfy-table

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

For https://github.com/stackabletech/stackablectl/issues/162

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by teozkr** [comment]
Looks like we now have different table formats for different commands?

Screenshot_20221125_160320

**Comment by sbernauer** [comment]
Good catch, that was a leftover! Used `ack 'use comfy_table::' -C 5 src` to check there are no others

**Review by maltesander — COMMENTED** [review]
The operator list command still uses simple prints. We wan to have it there as well for consistency? I know we talked about this but cannot really remember the outcome.

**Comment by sbernauer** [comment]
Good catch, fixed

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request closed without merging**
